title: Sowmya Chenthi Kumar # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Data Enthusiast - Masters in Data Science - University of British Columbia 
  <br><br>
 
  <a href="https://www.linkedin.com/in/sowmya-chenthi-kumar">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/Sowmya-Chenthi-Kumar">View my Github Profile</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
